name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  IMAGE_NAME: ghcr.io/${{ github.repository_owner }}/flask-demo

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - uses: actions/setup-python@v6
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run tests
        run: pytest tests/ -v
  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v6

      - name: Build image
        uses: docker/build-push-action@v7
        with:
          context: .
          push: false
          tags: ${{ env.IMAGE_NAME }}:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max # save cache to GitHub Actions for future builds
          load: true # load the built image into the Docker daemon for scanning

      - name: Save image
        run: docker save ${{ env.IMAGE_NAME }}:latest -o /tmp/image.tar

      - name: Upload image artifact
        uses: actions/upload-artifact@v7
        with:
          name: docker-image
          path: /tmp/image.tar
          retention-days: 1

  scan:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download image artifact
        uses: actions/download-artifact@v8
        with:
          name: docker-image
          path: /tmp

      - name: Load image
        run: docker load -i /tmp/image.tar

      - name: Run Trivy scan
        uses: aquasecurity/trivy-action@v0.36.0
        with:
          image-ref: ${{ env.IMAGE_NAME }}:latest
          format: table
          exit-code: "1"
          severity: CRITICAL
          ignore-unfixed: true

      - name: Upload Trivy results
        if: always()
        uses: actions/upload-artifact@v7
        with:
          name: trivy-results
          path: trivy-results.sarif
          retention-days: 7